# Generated by Django 3.0.2 on 2020-01-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('resources', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('aproved', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(to='comments.Comment')),
                ('resource', models.ManyToManyField(to='resources.Resource')),
                ('reviews', models.ManyToManyField(to='reviews.Review')),
            ],
        ),
    ]
