# Generated by Django 3.0.2 on 2020-01-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pontoturistico_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='aproved',
            new_name='approved',
        ),
    ]
